import ProviderWrapper from "@/providers/ProviderWrapper";
import type { Metadata } from "next";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "../resources/css/global.css";
import "../resources/css/normalize.css";
import "../resources/css/pretendard.css";
import "../resources/css/swiperStyle.css";

export const metadata: Metadata = {
  title: "Puffu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0"
        />
        <meta name="theme-color" content="#000" />
        <meta name="robots" content="index,follow" />
        <link rel="icon" href="/favicon.ico" />

        <meta name="description" content="특별한 밤을 위한 다양한 성인용품 | 당신만을 위한 뜨밤 상품 한가득! | 성인용품 전문 | 딜도, 오나홀 | 게이, 레즈 토이" />
        <meta property="og:url" content="https://puffutoy.com" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="특별한 밤을 위한 당신의 선택 푸푸토이" />
        <meta property="og:description" content="특별한 밤을 위한 다양한 성인용품 | 당신만을 위한 뜨밤 상품 한가득! | 성인용품 전문 | 딜도, 오나홀 | 게이, 레즈 토이" />
        <meta property="og:image" content="https://puffutoy.com/org-img.png" />

        <meta name="twitter:card" content="summary" />
        <meta name="twitter:title" content="K PUFFU | 普虎韩国" />
        <meta name="twitter:description" content="K PUFUFU(普虎韩国) offers Korean fashion (韩国服装), red ginseng (韩国红参), health food (韩国保健品), cosmetics (韩国护肤品), beauty (韩国妆), body care, and home appliances for global shoppers." />
        <meta name="twitter:image" content="https://puffukorea.com/org-img.png" />

        {/* <title>성인용품 | 푸푸토이 | 성인용품 전문점 | 입문자부터 숙련자까지!</title> */}
      </head>
      <body>
        <ProviderWrapper>
          {/*  */}
          {children}
          {/*  */}
        </ProviderWrapper>
      </body>
    </html>
  );
}
