import ProviderWrapper from "@/providers/ProviderWrapper";
import type { Metadata } from "next";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "../resources/css/global.css";
import "../resources/css/normalize.css";
import "../resources/css/pretendard.css";
import "../resources/css/swiperStyle.css";

export const metadata: Metadata = {
  title: "Puffu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0"
        />
        <meta name="theme-color" content="#000" />
        <meta name="robots" content="index,follow" />
      </head>
      <body>
        <ProviderWrapper>
          {/*  */}
          {children}
          {/*  */}
        </ProviderWrapper>
      </body>
    </html>
  );
}
