import ConfirmModal from "@/modals/confirm/ConfirmModal";
import ContextMenuModal from "@/modals/context/ContextMenuModal";
import ToastModal from "@/modals/toast/ToastModal";
import NiceModal from "@ebay/nice-modal-react";
import BannerModal from "./admin/banner/BannerModal";
import BrandModal from "./admin/brand/BrandModal";
import CategoriesModal from "./admin/category/CategoriesModal";
import CategoryListModal from "./admin/category/CategoryListModal";
import CategoryModal from "./admin/category/CategoryModal";
import CategorySelectModal from "./admin/category/CategorySelectModal";
import GroupModal from "./admin/group/GroupModal";
import LoadingModal from "./admin/LoadingModal";
import NoticeModal from "./admin/notice/NtoiceModal";
import OrderDetailModal from "./admin/order/OrderDetailModal";
import ProductModal from "./admin/product/ProductModal";
import VariantListModal from "./admin/product/VariantListModal";
import VariantModal from "./admin/product/VariantModal";
import PromotionModal from "./admin/promotion/PromotionModal";
import PromotionOptionListModal from "./admin/promotion/PromotionOptionListModal";
import PromotionOptionModal from "./admin/promotion/PromotionOptionModal";
import QAModal from "./admin/qa/QAModal";
import ShippingMethodDetailModal from "./admin/shipping_method/ShippingMethodDetailModal";
import ShippingMethodListModal from "./admin/shipping_method/ShippingMethodListModal";
import StoreModal from "./admin/store/StoreModal";
import OrderListModal from "./admin/user/OrderListModal";
import UserModal from "./admin/user/UserModal";
import InputModal from "./input/InputModal";
import ListModal from "./list/ListModal";
import AddressListModal from "./main/address/AddressListModal";
import AddressModal from "./main/address/AddressModal";
import PostalCodeModal from "./main/address/PostaCodelModal";
import OptionChangeModal from "./main/product/OptionChangeModal";
import PurchaseModal from "./main/product/PurchaseModal";
import ReviewWriteModal from "./main/review/ReviewWriteModal";
import SearchModal from "./main/search/SearchModal";
import SelectModal from "./main/select/SelectModal";
import TableModal from "./table/TableModal";
import TermContentModal from "./main/policies/TermContentModal";
import PraivacyContentModal from "./main/policies/PraivacyContentModal";
import ImgViewSliderModal from "./main/imgViewerSlider/imgViewSliderModal";

function ModalHandler() {
  NiceModal.register("toast", ToastModal);
  NiceModal.register("confirm", ConfirmModal);
  NiceModal.register("table", TableModal);
  NiceModal.register("list", ListModal);
  NiceModal.register("contextMenu", ContextMenuModal);
  NiceModal.register("input", InputModal);
  NiceModal.register("loading", LoadingModal);
  // main
  NiceModal.register("select", SelectModal);
  NiceModal.register("address", AddressModal);
  NiceModal.register("addressList", AddressListModal);
  NiceModal.register("search", SearchModal);
  NiceModal.register("purchase", PurchaseModal);
  NiceModal.register("postalcode", PostalCodeModal);
  NiceModal.register("optionChange", OptionChangeModal);
  NiceModal.register("reviewWrite", ReviewWriteModal);
  NiceModal.register("TermContent", TermContentModal);
  NiceModal.register("PraivacyContent", PraivacyContentModal);
  NiceModal.register("ImgViewSliderModal", ImgViewSliderModal);
  // admin
  NiceModal.register("bannerDetail", BannerModal);
  NiceModal.register("groupDetail", GroupModal);
  NiceModal.register("noticeDetail", NoticeModal);
  NiceModal.register("orderDetail", OrderDetailModal);
  NiceModal.register("orderList", OrderListModal);
  NiceModal.register("userDetail", UserModal);
  NiceModal.register("productDetail", ProductModal);
  NiceModal.register("promotionDetail", PromotionModal);
  NiceModal.register("promotionOptionList", PromotionOptionListModal);
  NiceModal.register("promotionOption", PromotionOptionModal);
  NiceModal.register("variantList", VariantListModal);
  NiceModal.register("variantDetail", VariantModal);
  NiceModal.register("storeDetail", StoreModal);
  NiceModal.register("brandDetail", BrandModal);
  NiceModal.register("categoryList", CategoryListModal);
  NiceModal.register("categorySelect", CategorySelectModal);
  NiceModal.register("categories", CategoriesModal);
  NiceModal.register("categoryDetail", CategoryModal);
  NiceModal.register("shippingMethodList", ShippingMethodListModal);
  NiceModal.register("shippingMethodDetail", ShippingMethodDetailModal);
  NiceModal.register("QADetail", QAModal);
  return <></>;
}

export default ModalHandler;
